### ISSUE TITLE
NameError numbers.Real in TH1.fillallw

### ISSUE THREAD

**Issue by drdavis** [scikit-hep/uproot-methods#2]
`TH1.fillallw` uses `numbers.Real` but doesn't import the `numbers` module

```python
In [33]: x.fillallw(np.random.randn(10),np.random.randn(10))
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-33-ddea8ee61580> in <module>()
----> 1 x.fillallw(np.random.randn(10),np.random.randn(10))

~/Software/Python/anaconda3/lib/python3.6/site-packages/uproot_methods/classes/TH1.py in fillallw(self, data, weights)
    183             data = numpy.array(data)
    184
--> 185         if isinstance(weights, numbers.Real):
    186             weights = numpy.empty_like(data)
    187

NameError: name 'numbers' is not defined
```

Also, out of curiosity, for a non array argument should `empty_like` be replaced with `ones_like` multiplied by the number?
```python
weights = numpy.ones_like(data) * weights
```

**Comment by jpivarski** [comment]
`numpy.ones_like(data) * weights` is the same as `numpy.full(data.shape, weights, dtype=data.dtype)` but the latter is one step. Also, we don't really want `dtype=data.dtype` because the type of the array `weights` should come from the scalar `weights`, not the `data`. I'll push this as version 0.0.9.

I'm still interested in your thoughts on the design— should there be four fill methods or one? The design is still malleable at this early stage.

**Comment by drdavis** [comment]
Being completely honest.. I found the issue just out of curiously browsing the code! Not a a specific use-case (yet 😃). In a project I'm working on we're using uproot to avoid a ROOT installation for our histogramming and plotting. Based on some existing tooling we have in ATLAS we do require ROOT histograms at some point in the pipeline.. that is part of the reason why I was browsing the code. For our existing use case.. going from an existing numpy-defined histogram to a ROOT TH1 will be our dependency. So personally, _filling_ histograms isn't a high priority, but in my opinion I wouldn't mind the idea of four filling methods. They intuitively make sense to me.

w.r.t. array programming vs numba filling -- these days my brain is mostly in array programming mode

**Comment by jpivarski** [comment]
Aha! We just added write support to uproot (histograms only), which takes a list of recognized Python types and converts them into TH1*. I hadn't thought of it, but converting Numpy's histogram format (a tuple of bin edges and contents) would make a lot of sense. Then you would just say

```python
rootfile = uproot.recreate("some.root")
rootfile["name"] = numpy.histogram(...)
```

and some.root would contain the histogram. (Probably better to use the `with` syntax, but you know what I mean.) Names always come from the key in the dict-like assignment, but if you want to add titles or other attributes, we could extend the tuple protocol to recognize the third item as a title string, etc. Are you interested?

If so, could you open "Write Numpy histograms to ROOT files" as an issue on the main uproot repo? Then I can implement it and you'll have a place for feedback if it doesn't work right away.

We've only tested writing of regular histograms, but Numpy doesn't tell you whether the bin edges are regular or not. We could try to infer it numerically, though that's prone to error (needs a tolerance parameter). Do you think they should always go to irregular bins in ROOT or should we attempt to identify regular cases? (Maybe I'm overstating the numerical precision issue— it's probably a linspace and repeating the same linspace should give identical floating point bin edges.)

**Comment by drdavis** [comment]
Hi Jim, this is indeed a very cool feature thanks a lot! Sorry for the delayed response, was traveling

**Comment by jpivarski** [comment]
No problem!

To keep you updated, I've been looking at a variety of histogramming libraries for Python (there are a lot of them) and I'm thinking of removing _all_ ability to change a histogram that has been pulled from a ROOT file. Instead, it would be converted into an object of one of the many histogramming libraries, so you can use that instead. Thus, I'd remove all four of the `fill` methods and make a lot of noise about conversions into objects like those from [physt](https://physt.readthedocs.io/en/latest/tutorial.html).

**Comment by eduardo-rodrigues** [comment]
Hi Jim, I should have commented on the spot, but anyway: I do not see the benefit of being special with histograms coming from ROOT. What is the drawback of having filling methods for them? To me a histogram is not an object frozen in time. The fact of having or not having fill methods is totally unrelated with conversions to other histograms from other packages.

**Comment by jpivarski** [comment]
The point is to not introduce another under featured histogram implementation when there are better ones out there. Having a few of the methods that an analyst would want leads them to believe that uproot's internal histograms are the right way of doing things. it's better to communicate early that they should seek a real histogram in package than for them to discover it with half an analysis based on stubs (that then have to be translated).

More generally, the design of a library is as much about what is excluded as what's included.

**Comment by eduardo-rodrigues** [comment]
So the package is more a bridge rather than part of a histogramming package. OK, thanks.

**Comment by jpivarski** [comment]
That's right. We're trying to develop a well-connected community, rather than an all-in-one solution. Even before I heard of Boost-Histogram, F.A.S.T., and Physt, my plan was to take users out of uproot into histbook. But now that I know about all of these libraries, we're going to see if we can interoperate better. (To be discussed at today's meeting.)
