### ISSUE TITLE
TH1.py index method wrongly assumes a regular binning 

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot-methods#24]
The `index` method in TH1.py's `Methods` assumes that the binning is always regular, which is not the case.

https://github.com/scikit-hep/uproot-methods/blob/0aae83f4fc16875332fa85ea08013cde7b840f0a/uproot_methods/classes/TH1.py#L140

I think that uproot-method should not provide this interface at all, since it tries to emulate the behavior of a ROOT histogram. I think uproot and uproot-method should focus on giving access to the data of ROOT objects, and not try to imitate their behavior.

**Comment by jpivarski** [comment]
That's correct. You can drop this method.

Originally, the TH1.Methods interface did all the normal histogram things, including filling. I came to the conclusion— exactly as you say— that it shouldn't, it should only be about supplying access, not general-purpose histogramming. This `index` function is a relic of that, which I must have overlooked in the cleaning.

**Comment by jpivarski** [comment]
But generally, you will find incorrect (or at least, overly strong) assumptions. The histogram interface is not mature, as the purpose of uproot was TTree data. These immaturities should be called out and fixed, but they shouldn't be too surprising.

**Comment by jpivarski** [comment]
Somehow, this was missed. `index` is now removed from TH1 and TH2 (version 0.3.2).
