### ISSUE TITLE
TH2 variances returned as a list not a 2 by 2 array

### ISSUE THREAD

**Issue by alasfar-lina** [scikit-hep/uproot-methods#30]
It is not possible to use the variances method effectivly for TH2 histograms ... as it does not return an array with the correct dimensions

**Comment by jpivarski** [comment]
Sorry for the wait. This fix went into PR #29, which will become version 0.3.2.

Many of the TH1 methods were recently updated to a Numpy interface. I've just done the same for the equivalent TH2 methods.

`th2f.numpy()` should now give you the same thing you'd have gotten from `numpy.histogram2d` (a 3-tuple of values, xedges, yedges).
