### ISSUE TITLE
TLorentzVectorArray.from_ptetaphim without unpacking

### ISSUE THREAD

**Issue by dguest** [scikit-hep/uproot-methods#41]
Right now I have a structured array which includes pt, eta, phi, and mass. I'm using this to build TLorentzVectors by unpacking

```
pt, eta, phi, m = [jets[x] for x in ['pt', 'eta', 'phi', 'm']]
flat = TLorentzVector.TLorentzVectorArray.from_ptetaphim(pt, eta, phi, m)
```

this seems like it creates an intermediate copy unnecessarily. Is there some way to build this directly from from a N * 4 numpy array?

**Comment by jpivarski** [comment]
We should be specific and differentiate between the Python objects representing (pointing to) arrays and the array bytes themselves. I believe this should not copy the array bytes themselves, but only make several new Python handles to it.

When a Numpy structured array (record array) is turned into a Table, its columns are separately identified by new single-column handles to the block of bytes, each with a 4*itemsize stride. Then when the Table is wrapped in an ObjectArray and maybe a JaggedArray, those columns are reused but not copied.

If you're seeing different behavior, I'd like to narrow down on where that is.

**Comment by dguest** [comment]
OK, I didn't realize how clever numpy was with the striding here but indeed you're correct. Sorry for the noise.

**Comment by jpivarski** [comment]
No problem!
