### ISSUE TITLE
from_ptetaphi() should be from_ptetaphie()

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/uproot-methods#69]
`TLorentzVector.from_ptetaphi()`'s signature is actually `pt, eta, phi, energy`. There's `from_ptetaphim()` for `pt, eta, phi, mass`, so one would expect the "e" to be in the first function's name. This would be more consistent with [ROOT's TLorentzVector](https://root.cern.ch/doc/master/classTLorentzVector.html#a6f5009aa2696a4e54eed4b29834ca3f0). Can we just add `from_ptetaphie()` as a synonym?

**Comment by jpivarski** [comment]
Yes.  :)

**Comment by masonproffitt** [comment]
Added by #70.
