### ISSUE TITLE
TH3 not yet implemented

### ISSUE THREAD

**Issue by marinang** [scikit-hep/uproot-methods#8]
Hi,
Is there a deep reason why TH3 is not yet implemented or there was not interest until now?
Matt

**Comment by marinang** [comment]
> Hi,
> Is there a deep reason why TH3 is not yet implemented or there was not interest yet?
> Matt

**Comment by jpivarski** [comment]
There's no deep reason. There are so many possible types to cover, each one useful to a subset of analyses, that we've been implementing then as-needed. In fact, it would be great if you can follow the pattern set by TH1 and TH2 to submit your own implementation as a PR. It's fine to only implement what you need.

**Comment by marinang** [comment]
All good then, I'll do It asap.
